kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-fs-pv
  labels:
    release: stable
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: {{ server_ip }}
    path: {{ server_path }}
