kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-fs-pv
  labels:
    release: stable
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 172.18.8.20
    path: /data/nfs/lib
