apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nexus3.fullname" . }}
  labels:
    app: {{ template "nexus3.name" . }}
    chart: {{ template "nexus3.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "nexus3.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "nexus3.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: nexus-ui
              containerPort: 8081
          resources:
{{ toYaml .Values.resources | indent 12 }}
