apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gitlab
  template:
    metadata:
      labels:
        name: gitlab
    spec:
      containers:
      - name: gitlab
        image: sameersbn/gitlab:11.1.4
        env:
        - name: TZ
          value: Asia/Shanghai

        - name: GITLAB_SECRETS_DB_KEY_BASE
          value: long-and-random-alpha-numeric-string
        - name: GITLAB_SECRETS_SECRET_KEY_BASE
          value: long-and-random-alpha-numeric-string
        - name: GITLAB_SECRETS_OTP_KEY_BASE
          value: long-and-random-alpha-numeric-string

        - name: GITLAB_ROOT_PASSWORD
          value: K2pass!!
        - name: GITLAB_ROOT_EMAIL
          value: admin@example.com

        - name: GITLAB_HOST
          value: git.paasdev.k2software.cn
        - name: GITLAB_PORT
          value: "80"
        - name: GITLAB_SSH_PORT
          value: "22"

        - name: GITLAB_NOTIFY_ON_BROKEN_BUILDS
          value: "true"
        - name: GITLAB_NOTIFY_PUSHER
          value: "false"

        - name: GITLAB_BACKUP_SCHEDULE
          value: daily
        - name: GITLAB_BACKUP_TIME
          value: 01:00

        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: postgresql
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: gitlab
        - name: DB_PASS
          value: passw0rd
        - name: DB_NAME
          value: gitlab_production

        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"

        - name: SMTP_ENABLED
          value: "false"
        - name: SMTP_DOMAIN
          value: mail.aliyun.com
        - name: SMTP_HOST
          value: smtp.aliyun.com
        - name: SMTP_PORT
          value: "25"
        - name: SMTP_USER
          value: 
        - name: SMTP_PASS
          value: 
        - name: SMTP_STARTTLS
          value: "false"
        - name: SMTP_AUTHENTICATION
          value: login

        - name: IMAP_ENABLED
          value: "false"
        - name: IMAP_HOST
          value: imap.gmail.com
        - name: IMAP_PORT
          value: "993"
        - name: IMAP_USER
          value: mailer@example.com
        - name: IMAP_PASS
          value: password
        - name: IMAP_SSL
          value: "true"
        - name: IMAP_STARTTLS
          value: "false"

        - name: LDAP_ENABLED
          value: "true"
        - name: LDAP_HOST
          value: "ldap-openldap-service"
        - name: LDAP_PORT
          value: "389"
        - name: LDAP_UID
          value: "cn"
        - name: LDAP_METHOD
          value: "plain"
        - name: LDAP_BIND_DN
          value: "cn=admin,dc=k2software,dc=cn"
        - name: LDAP_PASS
          value: "K2pass!!!"
        - name: LDAP_ALLOW_USERNAME_OR_EMAIL_LOGIN
          value: "false"
        - name: LDAP_BASE
          value: "ou=people,dc=k2software,dc=cn"
        - name: LDAP_USER_FILTER
          value: "(memberOf=ou=gitlab-users,ou=gitlab-groups,ou=groups,dc=k2software,dc=cn)"
        ports:
        - name: http
          containerPort: 80
        - name: ssh
          containerPort: 22
        volumeMounts:
        - mountPath: /home/git/data
          name: data
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: gitlab-pvc
