apiVersion: v1
kind: Service
metadata:
  name: gitlab-svc
  labels:
    name: gitlab-svc
spec:
  type: ClusterIP
  ports:
    - name: gitlab-svc-port
      port: 80
      targetPort: http
  selector:
    name: gitlab
