apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab-ing
spec:
  rules:
  - host: git.paasdev.k2software.cn
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab-svc
          servicePort: gitlab-svc-port
