apiVersion: v1
kind: Service
metadata:
  name: external-jira
spec:
  ports:
  - name: jira-port
    port: 8080
    protocol: TCP
  clusterIP: None
  type: ClusterIP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-jira
subsets:
- addresses:
  - ip: 172.19.7.148
  ports:
  - name: jira-port
    port: 8080
    protocol: TCP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jira-ing
spec:
  rules:
  - host: jira.paasdev.k2software.cn
    http:
      paths:
      - path: /
        backend:
          serviceName: external-jira
          servicePort: jira-port
