kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nexus-pvc
spec:
  storageClassName: nfs-dynamic-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nexus3
  namespace: default
  labels:
    app: nexus3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus3
  template:
    metadata:
      labels:
        app: nexus3
    spec:
      containers:
      - name: nexus3
        image: sonatype/nexus3:3.12.0
        volumeMounts:
        - name: nexus-data
          mountPath: /sonatype-work
        resources:
          requests:
            cpu: 800m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
        ports:
        - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 30
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 30
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-pvc
          
           

---
apiVersion: v1
kind: Service
metadata:
  name: nexus3
  namespace: default
  labels:
    app: nexus3
spec:
  type: NodePort
  selector:
    app: nexus3
  ports:
  - name: nexus-ui
    port: 8081
    nodePort: 30012
  - name: nexus-repo
    port: 5000
    nodePort: 30013
