apiVersion: v1
kind: Service
metadata:
  name: external-mysql
spec:
  ports:
  - name: mysql-port
    port: 3306
    protocol: TCP
  clusterIP: None
  type: ClusterIP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-mysql
subsets:
- addresses:
  - ip: 172.19.7.147
  ports:
  - name: mysql-port
    port: 3306
    protocol: TCP
