apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus2-pvc
spec:
  storageClassName: nfs-dynamic-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus2
  template:
    metadata:
      labels:
        app: nexus2
    spec:
      containers:
      - name: nexus2
        image: sonatype/nexus
        volumeMounts:
        - mountPath: /sonatype-work
          name: nexus2-volume
        ports:
        - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /nexus
            port: 8081
          initialDelaySeconds: 60
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /nexus
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5
          failureThreshold: 5
      volumes:
      - name: nexus2-volume
        persistentVolumeClaim:
          claimName: nexus2-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: nexus2-service
spec:
  type: ClusterIP
  selector:
    app: nexus2
  ports:
    - name: nexus2-port
      port: 8081
      targetPort: 8081

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nexus2
spec:
  rules:
  - host: nexus.paasdev.k2software.cn
    http:
      paths:
      - path: /
        backend:
          serviceName: nexus2-service
          servicePort: nexus2-port

