apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: owncloud-pvc
spec:
  storageClassName: nfs-dynamic-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
